In [1]:
pwd()

'C:\\Users\\mook\\Desktop\\bigdata\\tensorflow'

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

C:\Users\mook\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [10]:
#1. 초기화
node1 = tf.constant(3.0, tf.float32)
node2 = tf.constant(5.0, tf.float32)
node3 = tf.add(node1, node2)

print(node2)

#2. 실행
sess = tf.Session()
print(sess.run([node1, node2, node3]))

Tensor("Const_3:0", shape=(), dtype=float32)
[3.0, 5.0, 8.0]


In [13]:
# placeholder 설정
ph1 = tf.placeholder(tf.float32)
ph2 = tf.placeholder(tf.float32)
adder = ph1 + ph2

print(sess.run(adder, feed_dict={ph1 : [33,2,4], ph2: [2,1,4]}))

[35.  3.  8.]


In [16]:
print(sess.run(adder, feed_dict={ph1 : [[33,2,4],[2,1,3]], ph2: [[2,1,4],[4,2,1]]}))

[[35.  3.  8.]
 [ 6.  3.  4.]]


In [29]:
v1= tf.Variable(tf.random_normal([10,10], stddev=0.35))#리스트 안에 shape을 넣음
v2 = tf.Variable(tf.random_normal([4,2],stddev=0.22))
sess.run(tf.global_variables_initializer()) #variable을 쓸땐 항상 이걸로 초기화 해야함

In [4]:
sess1 = tf.InteractiveSession()
t = tf.constant([1,2,3,4])
print(t.eval())


[1 2 3 4]


In [5]:
mat1 = tf.constant([[1,2],[3,4]])
mat2 = tf.constant([[1],[2]])
print(tf.shape(mat1).eval())
print(mat1.eval())

print((mat1*mat2).eval())#행렬곱인지 브로드캐스팅 곱인지


[2 2]
[[1 2]
 [3 4]]
[[1 2]
 [6 8]]


In [6]:
x=[[1,2],[3,4]]
print(tf.reduce_mean(x).eval())
x=[[1.,2.],[3.,4.]]
print(tf.reduce_mean(x).eval())
print(tf.reduce_mean(x, axis=0).eval())
print(tf.reduce_mean(x, axis=1).eval())
print(tf.reduce_mean(x, axis=-1).eval())
print(tf.reduce_sum(x, axis=0).eval())
print(tf.reduce_sum(x, axis=1).eval())

2
2.5
[2. 3.]
[1.5 3.5]
[1.5 3.5]
[4. 6.]
[3. 7.]


In [7]:
# argmax => 가장큰 수가 있는 인덱스를 반환
x = [[0,1,2],[3,4,5]]
tf.argmax(x, axis=0).eval()

array([1, 1, 1], dtype=int64)

In [8]:
x = [[0,1,2],[3,4,5]]
tf.argmax(x, axis=1).eval()

array([2, 2], dtype=int64)

In [9]:
x = [1,2,3,4,5,6,7,8,9]
tf.reshape(x,[3,3]).eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# one_hot encoder
t = tf.one_hot([[0],[1],[2],[3],[4]], depth =4).eval()
t

array([[[1., 0., 0., 0.]],

       [[0., 1., 0., 0.]],

       [[0., 0., 1., 0.]],

       [[0., 0., 0., 1.]],

       [[0., 0., 0., 0.]]], dtype=float32)

In [6]:
t = tf.reshape(t,[-1,4]).eval()
print(t)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
# 타입 캐스팅


In [12]:
# stack
x=[1,4]
y=[5,3]
z=[1,3]
tf.stack([x,y,z]).eval()

array([[1, 4],
       [5, 3],
       [1, 3]])

In [13]:
# ~와 같은 shape의 행렬 만들기
x = [[1,3,4],[1,5,7],[6,3,4]]

print(tf.ones_like(x).eval())
print(tf.zeros_like(x).eval())

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [19]:
x= np.array([[1,2,3],[4,1,2]])
print(x.shape)
print(np.ndim(x))

a = np.zeros((10,10))
b = np.ones((10,10))
c = np.full((3,3,3,3),7)
print(c)
d = np.eye(3)
print(d)

(2, 3)
2
[[[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]


 [[[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]

  [[7 7 7]
   [7 7 7]
   [7 7 7]]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
np.random.random((3,3))
#tf.random_normal



array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [24]:
# linspace => 0~20사이를 20개구간으로 나눔
np.linspace(0,20,20)


array([ 0.        ,  1.05263158,  2.10526316,  3.15789474,  4.21052632,
        5.26315789,  6.31578947,  7.36842105,  8.42105263,  9.47368421,
       10.52631579, 11.57894737, 12.63157895, 13.68421053, 14.73684211,
       15.78947368, 16.84210526, 17.89473684, 18.94736842, 20.        ])

In [26]:
# 2차원 슬라이싱
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
# 2,3 5,6만 슬라이싱 해봐
print(x[:2,1:])
#각 원소 맨끝만
print(x[:,2:])

[[2 3]
 [5 6]]
[[3]
 [6]
 [9]]


In [31]:
# RESHAPE
arr =np.arange(12).reshape(4,3)
print(arr)
row_mean = arr.mean(axis=1).reshape(4,1)
k = arr-row_mean ## normalize하는 기법으로도 쓰임
print(k)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
