In [2]:
import tensorflow as tf
import numpy as np

C:\Users\mook\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
sess = tf.InteractiveSession()
t = tf.constant([1,2,3,4])
print(t.eval())


[1 2 3 4]


In [8]:
mat1 = tf.constant([[1,2],[3,4]])
mat2 = tf.constant([[1],[2]])
print(tf.shape(mat1).eval())
print(mat1.eval())

print((mat1*mat2).eval())#행렬곱인지 브로드캐스팅 곱인지


[2 2]
[[1 2]
 [3 4]]
[[1 2]
 [6 8]]


In [15]:
x=[[1,2],[3,4]]
print(tf.reduce_mean(x).eval())
x=[[1.,2.],[3.,4.]]
print(tf.reduce_mean(x).eval())
print(tf.reduce_mean(x, axis=0).eval())
print(tf.reduce_mean(x, axis=1).eval())
print(tf.reduce_mean(x, axis=-1).eval())
print(tf.reduce_sum(x, axis=0).eval())
print(tf.reduce_sum(x, axis=1).eval())

2
2.5
[2. 3.]
[1.5 3.5]
[1.5 3.5]
[4. 6.]
[3. 7.]


In [18]:
# argmax => 가장큰 수가 있는 인덱스를 반환
x = [[0,1,2],[3,4,5]]
tf.argmax(x, axis=0).eval()

array([1, 1, 1], dtype=int64)

In [19]:
x = [[0,1,2],[3,4,5]]
tf.argmax(x, axis=1).eval()

array([2, 2], dtype=int64)

In [22]:
x = [1,2,3,4,5,6,7,8,9]
tf.reshape(x,[3,3]).eval()

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
# one_hot encoder
t = tf.one_hot([[0],[1],[2],[3],[4]], depth =4).eval()
t = tf.reshape(t,[-1,4]).eval()
print(t)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [4]:
# stack
x=[1,4]
y=[5,3]
z=[1,3]
tf.stack([x,y,z]).eval()

array([[1, 4],
       [5, 3],
       [1, 3]])

In [6]:
x = [[1,3,4],[1,5,7],[6,3,4]]

print(tf.ones_like(x).eval())
print(tf.zeros_like(x).eval())

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
